hackmd_db_postgres:
  image: postgres
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
    - POSTGRES_DB=hackmd
hackmd:
  build: hackmd
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
  links:
    - hackmd_db_postgres
  ports:
    - "3000:3000"
